---
- include_tasks:        '../tasks/template_files.yml'
- include_tasks:        '../tasks/symlinks.yml'
- include_tasks:        '../tasks/restart_services.yml'
  when:                 template_files_result.changed
                        or symlinks_result.changed
