---
- include_tasks:        'tasks/common/template_files.yml'
- include_tasks:        'tasks/common/symlinks.yml'
- include_tasks:        'tasks/common/restart_services.yml'
  when:                 template_files_result.changed
                        or symlinks_result.changed
